### ISSUE TITLE
Support uploading package to pypi

### ISSUE THREAD

**Issue by ShiKaiWi** [CeresDB/ceresdb-client-py#11]
To deliver the sdk to users, We have to upload the package to pypi. What we should do:
- Do the necessary application to pypi.
- Build an automatic upload procedure.

Maybe we should refer to some other famous python project.

**Comment by ShiKaiWi** [comment]
@messense Would you like provide some suggestions?

**Comment by messense** [comment]
https://github.com/CeresDB/ceresdb-client-py/blob/02719e2a7d70a3bd0bb183f965b2ab52b3e3b0f8/.github/workflows/release.yml#L47-L65

It's already there, but you need to configure the `PYPI_TOKEN` secret. Push a tag will trigger it.

**Comment by messense** [comment]
I wonder if we should rename the Python package name to `ceresdb_client`, the `_py` suffix is redundant. It's much nicer to write `import ceresdb_client` instead of `import ceresdb_client_py`.

**Comment by ShiKaiWi** [comment]
> I wonder if we should rename the Python package name to `ceresdb_client`, the `_py` suffix is redundant. It's much nicer to write `import ceresdb_client` instead of `import ceresdb_client_py`.

Actually, ceresdb_client_py is just the name of this repository and the package name should be `ceresdb_client`.

**Comment by ShiKaiWi** [comment]
I find that the project name is `ceresdb_client_py` and I will fix it:
https://github.com/CeresDB/ceresdb-client-py/blob/02719e2a7d70a3bd0bb183f965b2ab52b3e3b0f8/pyproject.toml#L2

**Comment by messense** [comment]
It's more than that name change, I'll send a PR soon.

**Comment by messense** [comment]
To get a [pypi api token](https://pypi.org/help/#apitoken) for this project, you can run `maturin sdist -o dist` locally (you can change the version in Cargo.toml to 0.0.0 first because we may not want to ship a v0.1.0 right now) and upload `dist/*.tar.gz` file using twine to register the package under your PyPI account. After that you can generate a new api token for this project in pypi.org dashboard.

```bash
maturin sdist -o dist
pip3 install twine
twine upload dist/*.tar.gz
```

**Comment by ShiKaiWi** [comment]
> To get a [pypi api token](https://pypi.org/help/#apitoken) for this project, you can run `maturin sdist -o dist` locally (you can change the version in Cargo.toml to 0.0.0 first because we may not want to ship a v0.1.0 right now) and upload `dist/*.tar.gz` file using twine to register the package under your PyPI account. After that you can generate a new api token for this project in pypi.org dashboard.
> 
> ```shell
> maturin sdist -o dist
> pip3 install twine
> twine upload dist/*.tar.gz
> ```

I'm registering pypi account.

**Comment by ShiKaiWi** [comment]
Already upload version 0.0.0 client: https://pypi.org/project/ceresdb-client/. and we are preparing to release 0.1.0 after #13 merged.

Thanks for your guidance. @messense
